# Generated by Django 4.2.30 on 2026-04-23 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('evaluado', 'Evaluado')], default='en_progreso', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación')),
                ('feedback', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sesión de Caso',
                'verbose_name_plural': 'Sesiones de Casos',
            },
        ),
        migrations.CreateModel(
            name='ManagementCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción del caso')),
                ('category', models.CharField(choices=[('conflicto', 'Manejo de Conflictos'), ('comunicacion', 'Comunicación Efectiva'), ('delegacion', 'Delegación'), ('motivacion', 'Motivación de Equipos'), ('decision', 'Toma de Decisiones'), ('cambio', 'Gestión del Cambio')], max_length=30, verbose_name='Categoría')),
                ('difficulty', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20, verbose_name='Dificultad')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_competencies', models.TextField(blank=True, verbose_name='Competencias clave a evaluar')),
            ],
            options={
                'verbose_name': 'Caso Gerencial',
                'verbose_name_plural': 'Casos Gerenciales',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente IA'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.casesession')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='casesession',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cases.managementcase'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
