# Generated by Django 4.2.30 on 2026-05-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesession',
            name='feedback',
        ),
        migrations.AddField(
            model_name='casesession',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casesession',
            name='coach_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesession',
            name='coach_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesession',
            name='coach_verdict',
            field=models.TextField(blank=True, verbose_name='Dictamen del Coach'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='ia_feedback',
            field=models.TextField(blank=True, verbose_name='Retroalimentación IA'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('quick_reply', 'Respuesta Rápida'), ('error_ia', 'Error de IA'), ('system_info', 'Info del Sistema')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='quick_reply_option',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntuación IA'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado — pendiente revisión coach'), ('en_revision', 'En Revisión por Coach'), ('evaluado', 'Evaluado')], default='en_progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='managementcase',
            name='key_competencies',
            field=models.TextField(blank=True, verbose_name='Competencias clave'),
        ),
        migrations.CreateModel(
            name='IAErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('notified_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error de IA',
                'verbose_name_plural': 'Errores de IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado — esperando nivel'), ('nivel_asignado', 'Nivel Asignado')], default='en_progreso', max_length=20)),
                ('current_question', models.IntegerField(default=1)),
                ('ia_level_suggestion', models.CharField(blank=True, max_length=20)),
                ('ia_summary', models.TextField(blank=True, verbose_name='Resumen IA del diagnóstico')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Diagnóstico',
                'verbose_name_plural': 'Sesiones de Diagnóstico',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'IA')], max_length=10)),
                ('content', models.TextField()),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.diagnosissession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
