# Generated by Django 4.2.30 on 2026-06-13 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_diagnosis_coach_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesession',
            old_name='coach_approved',
            new_name='mae_approved',
        ),
        migrations.RenameField(
            model_name='casesession',
            old_name='coach_reviewed_at',
            new_name='mae_reviewed_at',
        ),
        migrations.RenameField(
            model_name='diagnosissession',
            old_name='coach_approved',
            new_name='mae_approved',
        ),
        migrations.RenameField(
            model_name='diagnosissession',
            old_name='coach_reviewed_at',
            new_name='mae_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='casesession',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='casesession',
            name='coach_verdict',
        ),
        migrations.RemoveField(
            model_name='diagnosissession',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='diagnosissession',
            name='coach_verdict',
        ),
        migrations.AddField(
            model_name='casesession',
            name='current_phase',
            field=models.CharField(choices=[('ambiguity', 'Fase 1: Ambigüedad'), ('pressure', 'Fase 2: Presión'), ('dilemma', 'Fase 3: Dilema'), ('completed', 'Fases Completadas')], default='ambiguity', max_length=20),
        ),
        migrations.AddField(
            model_name='casesession',
            name='mae',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mae'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casesession',
            name='mae_verdict',
            field=models.TextField(blank=True, verbose_name='Dictamen del MAE'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_time_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de respuesta (seg)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='total_pause_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo en pausa (seg)'),
        ),
        migrations.AddField(
            model_name='diagnosissession',
            name='mae',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mae'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosissession',
            name='mae_verdict',
            field=models.TextField(blank=True, verbose_name='Dictamen del MAE sobre el diagnóstico'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado — pendiente revisión MAE'), ('en_revision', 'En Revisión por MAE'), ('evaluado', 'Evaluado')], default='en_progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosissession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado — esperando revisión MAE'), ('aprobado', 'Aprobado por MAE'), ('rechazado', 'Rechazado por MAE'), ('nivel_asignado', 'Nivel Asignado')], default='en_progreso', max_length=20),
        ),
    ]
