# Generated by Django 4.2.30 on 2026-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_coach_approved_casesession_mae_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100, verbose_name='Nombre')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai_compatible', 'OpenAI / Compatible')], default='gemini', max_length=20, verbose_name='Proveedor')),
                ('api_url', models.URLField(help_text='URL completa del endpoint de la API', verbose_name='URL del endpoint')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, help_text='Solo para OpenAI/compatibles. Ej: gpt-4o, deepseek-chat', max_length=100, verbose_name='Nombre del modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuraciones de IA',
            },
        ),
    ]
