# Generated by Django 4.2.30 on 2026-06-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_add_ai_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('en_revision', 'En Revisión por MAE'), ('evaluado', 'Evaluado')], default='en_progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosissession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Esperando validación del MAE'), ('aprobado', 'Aprobado por MAE'), ('rechazado', 'Rechazado por MAE'), ('nivel_asignado', 'Nivel Asignado')], default='en_progreso', max_length=20),
        ),
    ]
