# Generated by Django 4.2.30 on 2026-06-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_casesession_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('groq', 'Groq'), ('mistral', 'Mistral AI'), ('together', 'Together AI'), ('openai_compatible', 'Otro (OpenAI Compatible)')], default='gemini', max_length=20, verbose_name='Proveedor'),
        ),
    ]
