# Generated by Django 4.2.30 on 2026-06-20 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0007_expand_provider_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesession',
            name='score',
        ),
        migrations.AddField(
            model_name='casesession',
            name='abandonment_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casesession',
            name='abandonment_reason',
            field=models.CharField(blank=True, choices=[('electrical_failure', 'Falla eléctrica'), ('internet_loss', 'Pérdida de internet'), ('user_frustration', 'Frustración del usuario'), ('other', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casesession',
            name='acumulado_ac',
            field=models.IntegerField(default=0, verbose_name='Variable Ac: Acoplamientos Exitosos'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='acumulado_sm',
            field=models.IntegerField(default=0, verbose_name='Variable Sm: Sincronía Metódica'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='acumulado_ts',
            field=models.IntegerField(default=0, verbose_name='Variable Ts: Trauma Sistémico'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesession',
            name='n_interactions',
            field=models.IntegerField(default=0, verbose_name='Variable n: total de ciclos'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='nchs_score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, verbose_name='Índice NC_hs'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ai_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='backspace_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conteo de backspaces'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='classification_variable',
            field=models.CharField(blank=True, choices=[('Ac', 'Acoplamiento Exitoso'), ('Sm', 'Sincronía Metódica'), ('Ts', 'Trauma Sistémico')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='entropy_node',
            field=models.CharField(choices=[('ambiguity', 'Ambigüedad'), ('time_pressure', 'Presión Temporal'), ('ethical_dilemma', 'Dilema Ético')], default='ambiguity', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latency_execution_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de ejecución (ms)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latency_reading_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de lectura (ms)'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('en_revision', 'En Revisión por MAE'), ('evaluado', 'Evaluado'), ('abandoned', 'Abandonada')], default='en_progreso', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(max_length=100, verbose_name='Grado académico')),
                ('institution_origin', models.CharField(max_length=100, verbose_name='Institución de origen')),
                ('research_line', models.CharField(max_length=150, verbose_name='Línea de investigación')),
                ('is_active_tutor', models.BooleanField(default=True, verbose_name='Tutor activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfiles de Docentes',
            },
        ),
        migrations.CreateModel(
            name='PreEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceived_control_score', models.IntegerField(verbose_name='Control percibido (1-5)')),
                ('ia_trust_baseline', models.IntegerField(verbose_name='Confianza en IA (1-5)')),
                ('initial_ego_statement', models.TextField(verbose_name='Declaración del ego inicial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_evaluation', to='cases.casesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-evaluación',
                'verbose_name_plural': 'Pre-evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='PostAutopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shock_reflection', models.TextField(verbose_name='Reflexión del choque')),
                ('negotiation_strategy', models.TextField(verbose_name='Estrategia de negociación')),
                ('law_sovereignty', models.TextField(verbose_name='Ley 1: Protocolo de última palabra')),
                ('law_identity', models.TextField(verbose_name='Ley 4: Elemento inalterable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_autopsy', to='cases.casesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_autopsies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post-autopsia',
                'verbose_name_plural': 'Post-autopsias',
            },
        ),
        migrations.AddField(
            model_name='casesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sessions', to='cases.teacherprofile'),
        ),
    ]
