# Generated by Django 4.2.30 on 2026-06-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_casesession_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesession',
            name='mae_verdict',
            field=models.TextField(blank=True, verbose_name='Dictamen del Docente Tutor'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('en_revision', 'En Revisión por Docente Tutor'), ('evaluado', 'Evaluado'), ('abandoned', 'Abandonada')], default='en_progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosissession',
            name='mae_verdict',
            field=models.TextField(blank=True, verbose_name='Dictamen del Docente Tutor sobre el diagnóstico'),
        ),
        migrations.AlterField(
            model_name='diagnosissession',
            name='status',
            field=models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Esperando validación del Docente Tutor'), ('aprobado', 'Aprobado por Docente Tutor'), ('rechazado', 'Rechazado por Docente Tutor'), ('nivel_asignado', 'Nivel Asignado')], default='en_progreso', max_length=20),
        ),
    ]
