# Generated by Django 4.2.30 on 2026-06-24 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0009_alter_casesession_mae_verdict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesession',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='sla_breached',
            field=models.BooleanField(default=False, verbose_name='SLA vencido'),
        ),
        migrations.AddField(
            model_name='casesession',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite SLA'),
        ),
        migrations.AddField(
            model_name='managementcase',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='managementcase',
            name='sla_hours',
            field=models.IntegerField(default=48, help_text='Horas máximas para revisión por el Docente Tutor', verbose_name='SLA (horas límite)'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('en_validacion', 'En Validación'), ('observado', 'Observado'), ('corregido', 'Corregido'), ('escalado', 'Escalado'), ('cerrado', 'Cerrado'), ('abandoned', 'Abandonada')], default='nuevo', max_length=30),
        ),
        migrations.CreateModel(
            name='CaseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Sesión creada'), ('status_change', 'Cambio de estado'), ('reviewed', 'Revisado'), ('observed', 'Observación registrada'), ('approved', 'Aprobado'), ('rejected', 'Devuelto'), ('corrected', 'Corrección recibida'), ('escalated', 'Escalado'), ('closed', 'Cerrado')], max_length=20, verbose_name='Acción')),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('observation', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.casesession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Caso',
                'verbose_name_plural': 'Auditorías de Casos',
                'ordering': ['-created_at'],
            },
        ),
    ]
