# Generated by Django 4.2.30 on 2026-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_update_legacy_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesession',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 del caso + la transcripción completa, calculado al cerrar la sesión. Detecta sesiones con contenido idéntico a otra ya existente.', max_length=64, null=True, unique=True, verbose_name='Hash del contenido'),
        ),
    ]
