# Generated by Django 4.2.30 on 2026-09-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_casesession_content_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosismessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensaje de Diagnóstico', 'verbose_name_plural': 'Mensajes de Diagnóstico'},
        ),
    ]
