# Generated by Django 4.2.30 on 2026-05-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='diagnosis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='level',
            field=models.CharField(choices=[('sin_nivel', 'Sin nivel asignado'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='sin_nivel', max_length=20, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='level_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='main_challenge',
            field=models.TextField(blank=True, verbose_name='Principal reto'),
        ),
    ]
