# Generated by Django 4.2.30 on 2026-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_managerprofile_diagnosis_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mae', 'MAE'), ('gerente', 'Gerente')], default='gerente', max_length=20),
        ),
    ]
